# Generated by Django 3.0.8 on 2020-07-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemsSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Название товара')),
                ('description', models.TextField(verbose_name='Описание')),
                ('img', models.ImageField(blank=True, upload_to='items_slider/')),
                ('is_active', models.BooleanField(default=True, verbose_name='Отображение товара')),
            ],
            options={
                'verbose_name': 'Объекты для слайдера',
            },
        ),
    ]
